### ISSUE TITLE
Paper: The Diversity–Innovation Paradox in Science

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#116]
https://www.pnas.org/content/117/17/9284

This paper is quite interesting. They model theses into topics and then examine when links between topics were first made, the distance between those topics in an embedding space, and then the eventual uptake of these links.

They find that underrepresentation is associated with introducing more distal links, but that for women and non-white scientists those links are more likely to receive less uptake (Fig 2F).

One piece of feedback that I have received over and over again from ISCB leadership is that the disparities might not be a problem, as they might reflect real academic value. We have also seen this in our reviews from anonymous reviewers. As a member of ISCB's Equity, Diversity, and Inclusion committee I saw this prompt conveyed to us based on our manuscript: "Are there recommendations from the committee that could guide ISCB in improving its diversity and still maintain fair science review?" This is a misunderstanding of our main point, which is actually that ISCB's disparities arise from failing to maintain fair scientific review.

I think we've done a nice job of pointing out that the perceived value that scientific advances have is conveyed by peers and the community, and if the selection process results in a group that fails to reflect the diversity of the field then that's a failure of the selection process. This paper aligns with that and suggests that discounting the contributions of minority scientists is causing us to miss promising advances. Their conclusions note:
> We reveal a stratified system where underrepresented groups have to innovate at higher levels to have similar levels of career likelihoods. These results suggest that the scientific careers of underrepresented groups end prematurely despite their crucial role in generating novel conceptual discoveries and innovation.

We should make sure to discuss this when we have the opportunity to revise the work in response to the critiques.

**Comment by trangdata** [comment]
Super neat method to measure novelty and corresponding impact! Their findings corroborate our point on the importance of peer recognition and how much it affects a scientist's career.

> "Are there recommendations from the committee that could guide ISCB in improving its diversity and still maintain fair science review?" This is a misunderstanding of our main point, which is actually that ISCB's disparities arise from failing to maintain fair scientific review.

Yes!!! I would also like to make this point clearer in the revision.
