### ISSUE TITLE
Add curation data to Wikidata too?

### ISSUE THREAD

**Issue by lubianat** [greenelab/iscb-diversity-manuscript#138]
Hello, congrats on the work! 

Wikidata has a good system for this kind of metascientific information (via <https://scholia.toolforge.org/>), would you be interested to put your curation there too? 

It could lead to some interesting SPARQL queries and take advantage of the other Linked Data on Wikidata. 

If you have a published table somewhere (e.g. on Zenodo with a DOI) containing: 
* the name of the speaker
* the conference and year of the Key note
* the source for the information (e.g. the conference website) 

I'd gladly make the reconciliation to the Wikidata IDs.

**Comment by trangdata** [comment]
Hi @lubianat thank you, and thank you for this request! 🙏🏽  🙌🏽 

Here's the GitHub link to the [keynotes (and fellows) table](https://github.com/greenelab/iscb-diversity/blob/master/data/iscb/keynotes.tsv).

Our data and analysis code has been deposited at https://doi.org/10.5281/zenodo.5014756, but please let me know if you would like a separate DOI for this table only.

Thank you so much for your help! 🚀  💯

**Comment by lubianat** [comment]
@trang1618 Nice! Awesome table, by the way. If the general DOI works for you, it works for me too. I have reconciled the names to Wikidata (most were automatically matched with success) on this Google Sheet:
- https://docs.google.com/spreadsheets/d/13-3E-iEa3_1AHzWE7JpTMPwWABoWtlnCDwU2MwCjEUc/edit?usp=sharing 

Whenever I have a couple of hours to spare, I'll write a script to add the conferences and the speakers to Wikidata :). I made a pilot there, information will appear under the ISMB conference series in the Scholia platform: 
- https://scholia.toolforge.org/event-series/Q6044067 

I'll add new items on Wikidata for each conference using information from Wikipedia (https://en.wikipedia.org/wiki/Intelligent_Systems_for_Molecular_Biology), and this might take a while (but will be fun). 

I'll keep you updated and thanks again for sharing the data!

**Comment by trangdata** [comment]
These all sound awesome, @lubianat! Thank you for your contribution to Wikidata! 🥇  🚀

**Comment by lubianat** [comment]
Done! The queries on Scholia are still a bit limited, but the data is there: https://scholia.toolforge.org/event-series/Q6044067 :) 

If you ever want to do some analysis using structured data on Wikidata, just let me know :)

**Comment by trangdata** [comment]
Amazing! Thank you again for your work!!! @lubianat And thanks for the offer! I'll definitely reach out when the time comes!

**Comment by cgreene** [comment]
This is awesome! 👏
