### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by trangdata** [greenelab/iscb-diversity-manuscript#15]
I wanted to compile different special cases that may affect our race/ethnicity and gender predictions.

- Names from Iberia (Spain and Portugal) vs. names from Spanish and Portuguese-speaking countries in Latin America.
- Women scientists who changed their last name to their husband's. If they have different race/ethnicity, this would affect the race/ethnicity prediction.
- Missing gender predictions: Hyphenated names are more unique and thus harder to gender match. Most of these names are predicted to be of Asian origin (87%). Of the 2673 author names that were not gender matched, approximately 25% has a hyphen and 50% has fewer than 4 characters which are likely initials (AB, A.B, A B).

**Comment by trangdata** [comment]
@cgreene What do you think about these last two discussion points? Perhaps we could put these together with the first limitations in Conclusion?

**Comment by cgreene** [comment]
Maybe mention them in the methods section? I guess I would wonder if they relate centrally to our findings (conclusion/discussion) or are more moderate caveats (methods).

**Comment by trangdata** [comment]
I think more caveats. Will add these tonight!
