### ISSUE TITLE
R1: technology not mature

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#38]
> There have been quite a lot of discussion on the methodological weakness of this paper following its release on bioRxiv. The Race and Ethnicity chapter was particularly controversial, for example mixing it with religious terms was clearly an important error. Therefore, even if interesting, the technology proposed in the paper has still to mature to produce reliable results.

**Comment by dhimmel** [comment]
I think the use of affiliations to detect countries for authors is a major improvement. Also we should consider refitting the nationality / name-origin model based on exactly the categories we'd like to analyze. I think this would address this reviewer's comments.
