### ISSUE TITLE
R1: first/corresponding author on field-specific journals is not meaningful

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#41]
> A second problem with this approach is the use of the first/corresponding author of papers as background. Honors are given to scientists with significant contributions, where significant can be highly quoted, or original, or correspond to a long trajectory. Aspects, that might not be necessarily correspond to publications in the mentioned three journals. Indeed, many keynote invitations are to authors in related fields not necessarily published in bioinformatics journals. The logic of the comparison is unclear to say the least.

**Comment by trangdata** [comment]
We selected these journals to establish a field-specific baseline (two ISCB partner and one field-specific) to represent the field of bioinformatics and computational biology. We agree that this baseline is not perfect and invited speakers certainly publish in other journals, we wanted to test whether the contributions of minoritized scientists in these journals are recognized (at conferences and when named Fellows). Further, we expect a similar increasing trend of minoritized scientists' contributions in related fields.
