### ISSUE TITLE
R1: conclusions are obvious

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#42]
> Additionally, the two main conclusions of the paper are so obvious that is difficult to understand the need of the paper. First, conferences and societies in the  field are doing an effort to maintain a healthy gender balance, even if clearly  far from perfect the interpretation of the results seems to show a positive trend. Instead of analysing the results he authors go into a very long discussion of the causes and consequences,  a discussion that is potentially more appropriate for an opinion paper than for a scientific paper in the conference. The second aspect, is the geographical bias. Yes, it is obvious that most of the speakers are white, the important question to understand the origin of the bias is if there are other more influential authors in the literature that the ones that have been selected in these conferences . The paper does not provide the necessary data to assess is this is the case. To assume that the ideal situation will be to have a number of invitations/honors  proportional to the number of papers by region does not make any sense from a scientific or from the conference organisation point of view.

**Comment by cgreene** [comment]
The comment notes:
> Additionally, the two main conclusions of the paper are so obvious that is difficult to understand the need of the paper. 

I agree that the lack of diversity has been readily apparent for some time. I curated the list of honorees in 2018 and have shared the issues with ISCB board of directors members for some time. I did not observe any changes for 2019 despite these private attempts to influence diversity.

Since our paper was released ISCB has released the 2020 set of fellows:
https://www.iscb.org/iscb-fellows
It is surprisingly large (2x larger than most years), includes two scientists with affiliations in Asia including the first ever with an affiliation in China, and should be more diverse than the past honorees in multiple ways.

The Award Winners also seem more diverse than past years: https://www.iscb.org/iscb-news-items/4249-2020-feb14-iscb-congratulates-2020-award-winners

I suspect that the need for the paper is to provide rigorous analysis in a public setting to back up what has been apparent to anyone who cared for some time: namely that the primary society that aims to represent us as computational biologists needs to do better. Now that this paper exists, changes have begun to appear.

**Comment by cgreene** [comment]
The upcoming analysis of affiliations from @trang1618 and @dhimmel will help to address the other points related to geographic disparities.

**Comment by trangdata** [comment]
Would it be okay with you if I paraphrased what you said here for the response to reviewers?

**Comment by cgreene** [comment]
Sounds good to me!
