### ISSUE TITLE
R2: figures 1/2 do not support the title (disparities)

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#44]
> Most of the technical content is around associating names to genders/geographic origin or curating publications.
> Figs 1 and 2 does not strongly support the title. The over-representation and under-representation has not been quantified, with the appropriate statistical measures.

**Comment by cgreene** [comment]
In the submitted version Figure 1 is the gender analysis and Figure 2 is the wru analysis. Figure 1 could do with an estimated composition w/ confidence intervals. Figure 2 on the other hand does have appropriate statistical measures and those measures clearly show the over- and under-representation that we discuss in the text.

**Comment by trangdata** [comment]
I agree. I have now added overall statistical measures in  #83 and #84.

I suggest we close this issue.

**Comment by cgreene** [comment]
Agree
