### ISSUE TITLE
R2: nationality/region groupings are unclear

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#45]
> 1. Nationality/region definition: Mixing of religion and geographic regions is somewhat confusing for the uninitiated.
> I would have certainly benefited by understanding a basis for this classification.
> Even in "Nameprism" that the authors cite, the basis is unclear.

**Comment by trangdata** [comment]
As @dhimmel mentioned in #38, in this revision, the use of affiliations to detect countries for authors is a major improvement that would complement existing analyses.
