### ISSUE TITLE
R2: difference b/w equity & diversity unclear

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#46]
> 2. I was not able to parse the subtle implications of "We suggest that considering equity may be more appropriate than strictly diversity" that the authors offer in the Conclusion section.

**Comment by trangdata** [comment]
How do you think we should clarify this?

**Comment by cgreene** [comment]
Diversity describes whether or not the contributors come from different backgrounds. In the context of this study, we examine diversity with respect to national affiliation, name origin, and gender. Equity relates to the concept of being fair and impartial. For example, considering equity in the context of gender would take into account systemic discrimination that individuals overcame make the achievements they have made when selecting honorees. With respect to diversity, we may be happy with a level of representation of women that is not worse than the literature; however, with respect to equity we would prefer to see honorees more closely reflect society.

**Comment by trangdata** [comment]
How about adding a sentence after this one to clarify, before we get into the different citations. Something like this:

"Specifically, although this study found similar levels of representation of women between the groups of authors and honorees (diversity), the system needs to consider and address the underlying causes and biases for the lower proportion of women in the field compared to that of society (equity)."

**Comment by cgreene** [comment]
"We suggest that considering equity may be more appropriate than strictly diversity. For example, we found similar representation of women between authors and honorees suggesting honoree diversity is similar to that of authors. However, if fewer women are in the field because of systemic factors that inhibit their participation, we would not have reached equity."

Maybe?
