### ISSUE TITLE
Manuscript Title

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#5]
The manuscript needs a title. Key results thus far:

* Gender has not reached parity.
* Asian honorees are under-represented.
* White honorees are over-represented.

The results thus far for other race/ethnic groups are hard to interpret. Our current analysis lumps the Iberian peninsula in with other Spanish and Portuguese speaking communities, which is likely to under-state the degree to which Latin American scientists are under-represented among honorees.

Our working title has been: "Analysis of ISCB Fellows and Keynotes Reveals Disparities"

**Comment by cgreene** [comment]
I went with the working title for now, but I would be happy to have one that is more assertion based.

**Comment by trangdata** [comment]
I'm brainstorming... How about 

"Overrepresentation of white scientists among ISCB Fellows and keynote speakers"

We could add "Underrepresentation of Asian scientists" as well but that may imply a slightly different emphasis compared to the study as a whole (other race/ethnicity or region).

**Comment by cgreene** [comment]
"White scientists are overrepresented among ISCB Fellows and keynote speakers"

Although we do look at gender as well, and it would be left out from those titles. Maybe what we have still has the key assertion in there ("reveals disparities").

**Comment by trangdata** [comment]
You're right... OK let's leave it as is for now!
