### ISSUE TITLE
R3: why use average demographic distribution?

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#54]
> p. 4, paragraph 4: Why is using the average demographic distribution a reasonable assumption to make?

The section in question is:
> However, in the case of names that were not observed in the census, the function’s behavior was to use the average demographic distribution from the census. We modified the function to return a status denoting that results were inconclusive instead.

**Comment by trangdata** [comment]
We modified the function to return NAs as to not use average demographic distribution.

**Comment by cgreene** [comment]
Yes. I thought this was clear too. The sentence explicitly says we didn't do what the reviewer didn't want. I probably wouldn't make changes here, but we might want to consider changing the final part to say "return a status denoting that results were inconclusive (NA) instead."

**Comment by cgreene** [comment]
Actually I'll go ahead and file this PR now. I think just seeing "NA" instead of prose might have triggered the recognition in the reviewer's mind that we did exactly what they're asking for.
