### ISSUE TITLE
R3: more statistics would be nice for race/ethnicity

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#55]
> p. 7, Figure 2: It would be better to see statistics provided as part of this analysis.  It strikes me that the problem at hand here is similar to sample-to-sample microbiome population analysis, which use rigorous statistics, and the same types of methods could be used for analysis in Fig. 2.  This level of statistical rigor is present as part of Figure 3, which was good to see.

The figure in question is the wru-based study of the field vs. honorees.

**Comment by trangdata** [comment]
I can add tables for effect size and pvalues in analysis notebooks, but these statistics would be redundant with these figures in main text.

**Comment by cgreene** [comment]
I agree it is redundant with the figures. I wouldn't make changes.

**Comment by cgreene** [comment]
It is possible this reviewer didn't notice that there were 95% confidence intervals. That would be consistent with other elements of the review.
