### ISSUE TITLE
R3: please provide a p-value instead of 95% confidence intervals

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#56]
> p. 9, Figure 4: The same point can be made here as for Figure 2.  It would be nice to see a statistical analysis and a p-value or two to justify claims beyond appealing to figures.

The figure in question is the analysis of name origins.

**Comment by trangdata** [comment]
moved to https://github.com/greenelab/iscb-diversity-manuscript/issues/94
