### ISSUE TITLE
R3: "other categories" is used but not defined

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#57]
> p. 9, Figure 4: The term "other categories" is used but these are never really defined (see previous point).  It would be good to do so, perhaps even in a supplement.

**Comment by trangdata** [comment]
As of the [current version](https://greenelab.github.io/iscb-diversity-manuscript/v/1608683e5a9a0e89380262dc18f27c32f65fe97f/), we clarify in the caption of Fig. 5 "Category O represents all other groups.", which I think is sufficient to close this issue.

**Comment by cgreene** [comment]
What about doing a link to the table of groups and calling it a day on this
one?
