### ISSUE TITLE
R4: out of scope for conference

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#58]
> This topic is out of scope for the proceedings of ISMB, at least by how I interpret the scope. It has its place in the published literature (I recommend with major revisions), but there is no methodology for or the analysis of molecular and biological data. Instead it is a study about the authors of such papers and broadly speaking it characterizes the recognition and reward system for their contributions to the field.

**Comment by trangdata** [comment]
I suggest closing this issue because it's irrelevant to other venues for submission.

**Comment by cgreene** [comment]
Agree!
