### ISSUE TITLE
R4: positive elements

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#59]
> Overall this is a clearly written manuscript on a clearly important topic. The work has merits and it presents simple conclusions, but it also has deficiencies in analysis and presentation of results that need to be addressed.
> 
> Positives:
> * Social trends in science are important to track and corrective measures are necessary when disparities are identified. The manuscript brings attention to these important issues.
> 
> * Societies should be kept in check and it is the responsibility of the members (and non-members) to appropriately expose problems and fix problems. It is difficult to strike the right tone and for most of the manuscript the authors did it well.
> 
> * The analysis is solid for the most part. The focus on corresponding authors is appropriate. I see no better way to address the issues of gender and race/ethnicity but to employ prediction. I'd assume this prediction is roughly correct for gender. I am less sure about race, ethnicity, religion, etc because a few queries at NamePrism did not convince me of a very high accuracy or satisfy me with its groupings. The authors use their own tool, but I have not queried it. Overall though, I am willing to accept that this works well on average to not impact broad conclusions. The authors recognized that.
> 
> * Although results might appear simple, substantial work has been completed.

**Comment by trangdata** [comment]
I suggest closing this, but maybe we can use some of these points in the new cover/rebuttal letter.

**Comment by cgreene** [comment]
Yep - definitely!
