### ISSUE TITLE
R4: which conferences are included is poorly justified

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#60]
> * The analysis focuses on ISCB, its fellows and its conferences. ISCB conferences are listed at: https://www.iscb.org/iscb-conferences however, justification was not provided as to why some conferences made it and others did not. PSB for example was assessed as international but this is hard to justify given its location patterns. GIW/ISCB-Asia is omitted, but no justification was given. This is of course of significant importance for the conclusions. Either justification or expanded analysis is needed.

**Comment by trangdata** [comment]
relates to #62
