### ISSUE TITLE
R4: background distribution != society membership

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#61]
> * The background in the study is created from the publications in well-selected journals (Bioinformatics, BMC Bioinformatics and PLOS Computational Biology). That background is appropriate and provides a useful characterization but is not necessarily the most appropriate. When one talks about a society, an alternative appropriate background would be the professional membership in that society (a society has responsibilities to recognize the work of its members well). The gender information in ISCB should be publicly available so the authors can check the trends and agreements with the current background. The authors could even be able to work out a solution with ISCB to apply the predictors to the data and more deeply test their hypotheses. The conclusions could hold or not and new patterns could emerge.

**Comment by trangdata** [comment]
I don't know if we want to do this, but I looked into the directory and it seems like we can only search but not download all the members:
https://www.iscb.org/cms_addon/member_tools/memberlist.php

Also, all my searches so far have only returned 0 or 1 result.

**Comment by cgreene** [comment]
I think it's the responsibility of the society to adequately reflect the field, and if it aims to be the global society it should reflect the field globally. I don't feel that this is the right baseline, because if we had a society that had a discriminatory track record we wouldn't want to give it a pass because it wasn't any more discriminatory than it used to be. I'm not saying that's the case here, I'm just saying that I think using the field baseline is more appropriate than membership.

**Comment by trangdata** [comment]
That is a good point. I wanted to look into the list of members to compare with what we have, but I'll go ahead and rephrase this for the response.
