### ISSUE TITLE
R4: ISCB conferences are not worldwide meetings

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#62]
> * Related to above, the selected journals for the background are of global reach (especially Bioinformatics because of rankings and $0 closed-access publication charges) whereas selected ISCB conferences (with their honorees) are more localized in Europe and North America for financial reasons. Considering the field as a whole, there are conferences that are limited to Asia, such as APBC or ISCB-Asia/Genome Informatics Workshop that are both of good quality and well known. APBC 2020 web site also shows that BMC Bioinformatics is among journals for their special issue. This suggests that the journals indeed better represent the field and that conferences are more geographically fragmented, including potentially ISCB conferences. This in turn means that the selection of conferences is critical for the outcome and appropriateness of this analysis. I think it would be appropriate to see a recognition of this fact in the manuscript and adjust the analysis.

**Comment by cgreene** [comment]
Back when I was preparing this list in the first place (September, 2018 - wow - just checked the version history), it was to make a point to ISCB's leadership that there were issues with diversity among their keynotes at ISMB. This meant that I only included ISMB keynotes. After multiple unsuccessful attempts to bring these issues to their attention, we decided to bring this to a broader audience to see if we could achieve change by working publicly instead of through private channels.

It probably makes the most sense to focus on the flagship meetings that are meant to represent the society globally. ISMB's webpage touts itself as "the flagship meeting of the International Society for Computational Biology (ISCB)." ISMB has been held in North America, Europe, Oceania, and South America. RECOMB is also a meeting with international reach, and it has been held in North America, Europe, and Asia.

I'd propose that we drop PSB from the analyses at this stage. It does cost us the opportunity to highlight the only meeting to date where every honoree has been a woman (PSB 2020), but it probably more accurately reflects the meetings of ISCB that aim to be global. I think it would also be justified to restrict ourselves even more (to ISCB Fellows and ISMB as the flagship meeting), but I think the case for including RECOMB is pretty strong.

**Comment by trangdata** [comment]
From [PSB welcome site](https://psb.stanford.edu/welcome/):

> The Pacific Symposium on Biocomputing (PSB) 2021 is an **international**, multidisciplinary conference for the presentation and discussion of current research in the theory and application of computational methods in problems of biological significance.

~~Hence, I am leaning toward keeping PSB. We could also think about adding GIW/ISCB-Asia.~~

Hmm I see now. All conferences seem to claim they're "international".

**Comment by cgreene** [comment]
Most conferences, even regional ones, are "international." GLBIO has been hosted in Toronto. What we want are conferences that aim to have a global reach. I think using the society-associated meetings that have moved around extensively across continents is probably the way to identify those that seek a global reach. It helps that one of these is a "flagship" meeting.
