### ISSUE TITLE
R4: women may already be overrepresented / add conf intervals / discuss

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#63]
> * Figure 1. There is no statistical analysis of this data. By eyeballing the graphs it looks like that women are not underrepresented as honorees, and might even be overrepresented. This should be discussed more formally (e.g. statistical tests) and confidence intervals or statistical significance should be provided much like in Figure 2, whatever the conclusions are.

**Comment by trangdata** [comment]
The last figure on the [gender analysis notebook](https://greenelab.github.io/iscb-diversity/09.visualize-gender.html) (updated with PSB removed, but similar before), one can argue that there are two years when female scientists were "overrepresented": 2007 and 2016. But we should note the underestimation of the number of women in the field.

I can add this figure in the main text as part B of the mentioned figure.
