### ISSUE TITLE
R4: a thought experiment about two groups

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#64]
> * This may or may not be a problem in this study, but suppose 10 random papers from group A are published by 5 different corresponding authors and another 10 random papers from group B by a single member of that group. The chances that the top scientist is from group A is not 50%. How was this potential problem accounted for? If not, the authors could state how this might impact the outcomes.

**Comment by trangdata** [comment]
This is not a potential problem in our study because we did not randomly select papers and randomly assign groupings. We considered all publications in the specified journals and treat them all equally.

I suggest we close.

**Comment by cgreene** [comment]
👍
