### ISSUE TITLE
R4: keynote speakers earlier to 2002 available

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#65]
> * Minor: the keynote speakers for ISMB can be found on ISCB's web site and AAAI web site prior to 2002.

**Comment by trangdata** [comment]
I can start looking for these missing speakers.

**Comment by trangdata** [comment]
Complete. Corrupted links and all but I managed 😅. 

If it's okay with you, we can close this issue now and will rerun all analysis once we figure out which conferences to consider.

**Comment by cgreene** [comment]
Agree! :-)
