### ISSUE TITLE
R4: abstract mentions only white overrepresentation

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#66]
> * The abstract lists only one conclusion in the last sentence: white scientists are overrepresented and non-white scientists are underrepresented. This strikes me as cherry picking of findings. The paper, if I understood correctly, also found that female scientists are not underrepresented. Given the current climate, wouldn't it also be a major conclusion that the honorees are reasonably distributed gender-wise? Instead, the conclusion is "but the proportion has not reached parity". This suddenly changes the focus from ISCB practices relative to the field to ISCB practices relative to the entire society, which is a different background distribution and one where ISCB has little influence on.

**Comment by cgreene** [comment]
The most robust finding of the paper is that white scientists are overrepresented among honorees and non-white scientists are underrepresented. I feel strongly that the primary finding should go into the abstract.

The reviewer also wants us to note that honorees are reasonably distributed gender-wise. I don't think this is true. We can say that honorees at least match the literature rate, but they are far from parity. This is precisely what we state. I feel that we strike the right balance here.

In some sense, I feel that as what is currently the foremost worldwide society for computational biology, ISCB should have as a mission to promote equity (or at least diversity). I'm not the only one who feels this way, their "Mission, Vision & Values" page notes Diversity as one of their values and even discusses a global diversity of membership and leadership:
https://www.iscb.org/iscb-mission-vision-values

**Comment by trangdata** [comment]
Perhaps we can add this to the abstract:

"Although we observe similar gender distributions between the group of honorees and authors, other biases might contribute to an underestimation of female scientists in the field, and the proportions have not reached parity".

**Comment by cgreene** [comment]
I like this point!
