### ISSUE TITLE
R4: a reader might interpret the whole system as discriminatory

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#67]
> * Introduction: "finding that minority scientists tend to apply for awards on topics with lower success rates [1] could be interpreted either as minority scientists select topics in more poorly funded areas or that majority scientists consider topics of particular interest to minority scientists as less worthy of funding." It might look inflammatory to use terminology "less worthy" here. Maybe this was meant in a narrow technical sense, but a reader might decide to go for a broad interpretation and assess that the whole system is discriminatory.

**Comment by cgreene** [comment]
I wrote that sentence. I did not mean it in a narrow technical sense. I feel that in the opening of the paper, readers should consider that the system at least might be discriminatory. I particularly wanted to frame it in a way that scientists who have always had privileged status might understand how those without that status might be disadvantaged in a system based on peer recognition.

We might rework that section some as it seems the point was not clear to another reviewer as well (see #49), but I do not think we should eliminate the message.

**Comment by trangdata** [comment]
How about this?

"[...] or that topics of particular interest to minority scientists are underappreciated by review."

**Comment by cgreene** [comment]
Well, I think it's really important to note that honors, grants, etc are based heavily on peer perception. This has lots of strengths because most external measures of impact are exceedingly lagging, but it does mean that we have to be proactive to avoid biases. If there's a way to retain that emphasis, then I'd be ok with it.

**Comment by trangdata** [comment]
I agree with you, and I'm fine with leaving it as is. We can discuss these points in the response.
