### ISSUE TITLE
R4: discuss how to better honor meritorious scientists

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#69]
> * I would like to see discussion on the topic of how ISCB should adjust to identify scientists that merit recognition but have fallen through the cracks so far? Can a data-driven help be of use?

**Comment by cgreene** [comment]
We do say this:
> Societies, both through their honorees and the individuals who deliver keynotes at their meetings, can play a positive role in improving the presence of female STEM role models, which, for example, may lead to higher persistence for undergraduate women in geoscience [23]. Efforts are underway to create Wikipedia entries for more female [24] and black, Asian, and minority scientists [25], which can help early-career scientists identify role models. We find that ISCB’s honorees and keynote speakers, though not yet reaching gender parity, appear to be more evenly split between men and women than the field as a whole. On the other hand, honorees include significantly fewer people of color than the field as a whole, and Asian scientists are dramatically underrepresented among honorees. Although we estimate the fraction of non-white and non-Asian authors to be relatively similar to the estimated honoree rate, we note that both are represented at levels substantially lower than in the US population. Societies can play a positive role in enhancing equity if they design policies to honor scientists in ways that counter these biases.

I wonder if we should just note that the type of data collected here might help them to identify the biases that are being exhibited so that they can design policies, selection committees, etc appropriately. I think this would just require a slight change to the last sentence.

**Comment by trangdata** [comment]
I agree. This would also help address the second part of #66, i.e. ISCB does have some influence on "the background distribution".

**Comment by trangdata** [comment]
I'm re-reading this issue, and I feel the reviewer might have just missed what we stated here already, unless they suggested an *algorithm* to identify these individuals, which is rather out of scope. I think we just need to point this out in our responses to reviewers.

**Comment by cgreene** [comment]
👍
