### ISSUE TITLE
R5: is representation driven by geography?

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#71]
> There are assumptions and analysis issues. Did the author check if the association between predicted race/ethnicity and author Affiliation?  Was Asian bias by country or ethnicity?  For example, are American-Asians represented in ISCB honorees but Asians who are geographically located in Asia under-represented. Is this associated with geographic attendance at ISCB meetings? One might expect local awardees in the host country. For example, the authors note that ISMB keynotes had more probability attributable to Israel, while RECOMB had more attributable to East Asian countries.

**Comment by trangdata** [comment]
The new affiliation analysis together with the race/ethnicity analysis in the group of US-affiliated authors/honorees help answer these exact questions. I think we can close this issue once the result of the latter is merged.

**Comment by cgreene** [comment]
Agree 👍
