### ISSUE TITLE
R5: were names manually checked for accuracy?

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#72]
> Given this small pool of 411, some names of which were duplicated (fellows and keynotes etc), were they manually checked for accuracy.

**Comment by cgreene** [comment]
I can't tell if this reviewer wants us to eyeball names and photos and to try to guess gender, name origin, etc or if the reviewer is worried that we've made typos.

**Comment by trangdata** [comment]
I think they meant the former, but if the latter, I think I did quite a thorough job checking for typos.

**Comment by cgreene** [comment]
Ok - if the former, then I don't think we should do it. Thanks for the second read!

**Comment by trangdata** [comment]
I'm fine with closing this.
