### ISSUE TITLE
R5: missing names are non-random & may not match skin color

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#73]
> There are non-random missing data. European Spanish/Portuguese/Italian are called Hispanic. Assignment of the race (white/black/Asian) based surname is difficult to extrapolate to a multi-cultural society where last name and skin color are maybe discordant.

**Comment by trangdata** [comment]
We acknowledged that our supervised learning approaches are neither error free nor bias free. We would also note that it would be a mistake to consider race equivalent to skin color: race, as analyzed in this study, is based on self-identification and is a complex topic with its own area of research. However, once again, we hope that the newly added affiliation analysis at the country level without groupings will complement the approaches in the earlier version of the study. By integrating different methods, we hope to mitigate the existing issues and discover insightful findings that correctly reflect the current representation diversity at conferences.
