### ISSUE TITLE
Exact method for computing confidence intervals of enrichment (RR)

### ISSUE THREAD

**Issue by trangdata** [greenelab/iscb-diversity-manuscript#89]
Currently, the confidence intervals of enrichment are estimated via var(log(RR)) by the delta method (1/x1 - 1/n1 + 1/x2 - 1/n2) and a small continuity-like correction is applied to avoid dividing by 0. A potentially better estimate is to use an exact method (e.g., as proposed [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4715482/)) that calculates a lower bound even when the estimate is at infinity.

WIP.

**Comment by cgreene** [comment]
Is there a way to do a bootstrap estimation? I'm imagining resampling honorees and authors and computing multiple times. I guess maybe there are too many authors for this to be efficient.

**Comment by trangdata** [comment]
Let me think about this more, but I don't know if bootstrapping would help with the infinity lower bound.
